verbatim:
  cabal-version: 2.2

name: uvmhs
version: 0.0.1.0

default-extensions:
  - ConstraintKinds
  - CPP
  - DefaultSignatures
  - DataKinds
  - DeriveGeneric
  - DeriveLift
  - EmptyCase
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImpredicativeTypes
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QualifiedDo
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - RebindableSyntax
  - ScopedTypeVariables
  - StandaloneDeriving
  - StarIsType
  - Strict
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - UnicodeSyntax
  - ViewPatterns

ghc-options:
  - -optP-Wno-nonportable-include-path
  - -Wall
  - -Wno-orphans
  - -Wno-star-is-type
  - -j2
  - -fno-prof-auto
  # when we want to build fast...
  # - -O0
  # when we want a slow optimized build...
  - -O2
  - -optc-O3
  - -fspecialise-aggressively
  - -fexpose-all-unfoldings
  - -fprint-potential-instances

dependencies:
  - base
  - bytestring
  - cassava
  - containers
  - directory
  - filepath
  - ghc-prim
  - process
  - QuickCheck
  - random
  - template-haskell
  - text
  - time
  - vector
  - th-lift-instances

flags:
  no-uvmhs-tests:
    description: Disables building tests, which increases compile times
    default: false
    manual: true

library:
  source-dirs: src
  when:
  - condition: (flag(no-uvmhs-tests))
    cpp-options: -DNO_UVMHS_TESTS

executable:
  source-dirs: src_run
  main: Main.hs
  dependencies: uvmhs

tests:
  all:
    source-dirs: src_test
    main: Main.hs
    dependencies: uvmhs
